version: '3.8'

services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices_network

  user_service:
    build: 
      context: ./user_service
    container_name: user_service
    ports:
      - "50051:50051"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_NAME=USER_SERVICE
      - LOG_LEVEL=INFO
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=userdb
      - JWT_SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - mongodb
    networks:
      - microservices_network

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    ports:
      - "50052:50052"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_NAME=ORDER_SERVICE
      - LOG_LEVEL=INFO
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=orderdb
    depends_on:
      - mongodb
    networks:
      - microservices_network

  main_service:
    build:
      context: ./main_service
    container_name: main_service
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_NAME=MAIN_SERVICE
      - LOG_LEVEL=INFO
      - JWT_SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - user_service
      - order_service
    networks:
      - microservices_network

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - main_service
      - user_service
      - order_service
    networks:
      - microservices_network

networks:
  microservices_network:
    name: microservices_network
    driver: bridge

volumes:
  mongodb_data:
